//===============================================================================
// Microsoft patterns & practices
//  Data Access Guide
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// This code released under the terms of the 
// Microsoft patterns & practices license (http://dataguidance.codeplex.com/license)
//===============================================================================


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviKokonut.Repository.Implementation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.Repo.Impl.Mongo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string DatabaseDoesNotExist {
            get {
                return ResourceManager.GetString("DatabaseDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking existence for productId={0}..
        /// </summary>
        internal static string ErrorCheckingProductExistence {
            get {
                return ResourceManager.GetString("ErrorCheckingProductExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving all categories..
        /// </summary>
        internal static string ErrorRetrievingAllCategories {
            get {
                return ResourceManager.GetString("ErrorRetrievingAllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving order for trackingId={0}..
        /// </summary>
        internal static string ErrorRetrievingOrderByTrackingId {
            get {
                return ResourceManager.GetString("ErrorRetrievingOrderByTrackingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving order history for historyId={0}..
        /// </summary>
        internal static string ErrorRetrievingOrderHistoryByHistoryId {
            get {
                return ResourceManager.GetString("ErrorRetrievingOrderHistoryByHistoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving orders history for customerId={0}..
        /// </summary>
        internal static string ErrorRetrievingOrdersHistoryForCustomerId {
            get {
                return ResourceManager.GetString("ErrorRetrievingOrdersHistoryForCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving product for productId={0}..
        /// </summary>
        internal static string ErrorRetrievingProductByProductId {
            get {
                return ResourceManager.GetString("ErrorRetrievingProductByProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving products for subcategoryId={0}..
        /// </summary>
        internal static string ErrorRetrievingProductsForSubcategoryId {
            get {
                return ResourceManager.GetString("ErrorRetrievingProductsForSubcategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving subcategories for categoryId={0}..
        /// </summary>
        internal static string ErrorRetrievingSubcategories {
            get {
                return ResourceManager.GetString("ErrorRetrievingSubcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving order history for trackingId={0}..
        /// </summary>
        internal static string ErrorSavingOrderHistory {
            get {
                return ResourceManager.GetString("ErrorSavingOrderHistory", resourceCulture);
            }
        }
    }
}
